// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AudioController from "./audio_controller"
application.register("audio", AudioController)

import CheckoutController from "./checkout_controller"
application.register("checkout", CheckoutController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PostFormController from "./post_form_controller"
application.register("post-form", PostFormController)

import RecordingController from "./recording_controller"
application.register("recording", RecordingController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
